[package]
name = "rust-minimal-server-docker"
version = "0.1.0"
edition = "2021"

[dependencies]
tide = "0.16"
async-std = { version = "1", features = ["attributes"] }
serde = { version = "1", features = ["derive"] }
glob = "0.3"
clap = { version = "4", features = ["derive"] }
